CREATE INDEX "card_set_id_idx" ON "card" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "card_created_at_idx" ON "card" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "favorite_user_id_idx" ON "favorite" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "favorite_card_id_idx" ON "favorite" USING btree ("card_id");--> statement-breakpoint
CREATE INDEX "favorite_created_at_idx" ON "favorite" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "flashcard_set_user_id_idx" ON "flashcard_set" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "flashcard_set_is_public_idx" ON "flashcard_set" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "flashcard_set_category_idx" ON "flashcard_set" USING btree ("category");--> statement-breakpoint
CREATE INDEX "flashcard_set_created_at_idx" ON "flashcard_set" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "flashcard_set_like_count_idx" ON "flashcard_set" USING btree ("like_count");--> statement-breakpoint
CREATE INDEX "flashcard_set_public_category_idx" ON "flashcard_set" USING btree ("is_public","category");--> statement-breakpoint
CREATE INDEX "folder_set_folder_id_idx" ON "folder_set" USING btree ("folder_id");--> statement-breakpoint
CREATE INDEX "folder_set_set_id_idx" ON "folder_set" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "folder_user_id_idx" ON "folder" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "folder_is_public_idx" ON "folder" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "folder_created_at_idx" ON "folder" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "practice_progress_user_id_idx" ON "practice_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "practice_progress_set_id_idx" ON "practice_progress" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "practice_progress_mode_idx" ON "practice_progress" USING btree ("mode");--> statement-breakpoint
CREATE INDEX "practice_progress_user_set_mode_idx" ON "practice_progress" USING btree ("user_id","set_id","mode");--> statement-breakpoint
CREATE INDEX "processed_image_original_url_idx" ON "processed_image" USING btree ("original_url");--> statement-breakpoint
CREATE INDEX "saved_set_user_id_idx" ON "saved_set" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "saved_set_set_id_idx" ON "saved_set" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "saved_set_created_at_idx" ON "saved_set" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "session_token_idx" ON "session" USING btree ("token");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "set_comment_set_id_idx" ON "set_comment" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "set_comment_user_id_idx" ON "set_comment" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "set_comment_created_at_idx" ON "set_comment" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "set_comment_is_pinned_idx" ON "set_comment" USING btree ("is_pinned");--> statement-breakpoint
CREATE INDEX "set_join_set_id_idx" ON "set_join" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "set_join_user_id_idx" ON "set_join" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "set_like_set_id_idx" ON "set_like" USING btree ("set_id");--> statement-breakpoint
CREATE INDEX "set_like_user_id_idx" ON "set_like" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_achievement_user_id_idx" ON "user_achievement" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_achievement_achievement_id_idx" ON "user_achievement" USING btree ("achievement_id");--> statement-breakpoint
CREATE INDEX "user_username_idx" ON "user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "user" USING btree ("email");